<?php

namespace Database\Seeders;

use App\Models\Breed;
use App\Models\SpeciesType;
use Illuminate\Database\Seeder;

class BreedSeeder extends Seeder
{
    private function seedBreedList(string $speciesId, array $breeds): void
    {
        $seen = [];

        foreach ($breeds as $breedName) {
            $name = trim((string) $breedName);
            if ($name === '') {
                continue;
            }

            $key = mb_strtolower($name);
            if (isset($seen[$key])) {
                continue;
            }
            $seen[$key] = true;

            Breed::updateOrCreate(
                ['species_id' => $speciesId, 'name' => $name],
                ['is_active' => true]
            );
        }
    }

    public function run(): void
    {
        $dog = SpeciesType::where('code', 'D')->first();
        $cat = SpeciesType::where('code', 'C')->first();

        if ($dog) {
            $this->seedBreedList($dog->id, [
                'Other',
                'Affenpinscher',
                'Afghan Hound',
                'Africanis',
                'Aidi',
                'Airedale Terrier',
                'Akbash Dog',
                'Akita',
                'Alano Espanol',
                'Alapaha Blue Blood Bulldog',
                'Alaskan Husky',
                'Alaskan Klee Kai',
                'Alaskan Malamute',
                'Alopekis',
                'American Bulldog',
                'American Cocker Spaniel',
                'American English Coonhound',
                'American Eskimo Dog',
                'American Foxhound',
                'American Hairless Terrier',
                'American Mastiff',
                'American Pit Bull Terrier',
                'American Staffordshire Terrier',
                'American Staghound',
                'American Water Spaniel',
                'American White Shepherd',
                'Anatolian Shepherd Dog',
                'Andalusian Hound',
                'Appenzeller Sennenhund',
                'Ariege Pointer',
                'Ariegeois',
                'Aspin',
                'Australian Stumpy Tail Cattle Dog',
                'Austrial Catte Dog',
                'Austrialian Bulldog',
                'Austrialian Kelpie',
                'Austrialian Shepherd',
                'Austrialian Terrier',
                'Austrian Black and Tan Hound',
                'Austrian Pincher',
                'Azawakh',
                'Barbet',
                'Basenji',
                'Basset Artesien Normand',
                'Basset Bleu de Gascogne',
                'Basset Fauve de Bretagne',
                'Basset Hound',
                'Bavarian Mountain Hound',
                'Beagle',
                'Beagle-Harrier',
                'Beaglier',
                'Bearded Collie',
                'Beauceron',
                'Bedlington Terrier',
                'Belgian Malinois',
                'Belgian Sheepdog',
                'Belgian Shepherd Laekenois',
                'Belgian Tervuren',
                'Bergamasco',
                'Berger Picard',
                'Bernese Mountain Dog',
                'Bichon Frise',
                'Biewer Terrier',
                'Black and Tan Coonhound',
                'Black Mouth Cur',
                'Black Norwegian Elkhound',
                'Black Russian Terrier',
                'Bloodhound',
                'Blue Lacy',
                'Blue Picardy Spaniel',
                'Bluetick Coonhound',
                'Boerbel',
                'Bohemian Shepherd',
                'Bolognese dog',
                'Border Collie',
                'Border Terrier',
                'Borzoi',
                'Boston Terrier',
                'Bouvier des Ardennes',
                'Bouvier des Flandres',
                'Boxer',
                'Boykin Spaniel',
                'Bracco Italiano',
                'Braque du Bourbonnais',
                'Brazilian Terrier',
                'Briad',
                'Briquet Griffon Verdeen',
                'Brittany',
                'Broholmer',
                'Brussels Griffon',
                'Bukovina Sheepdog',
                'Bulgarian Shepherd Dog',
                'Bull Arab',
                'Bull Terrier',
                'Bulldog',
                'Bullmastiff',
                'Cairmal',
                'Cairn Terrier',
                'Canaan Dog',
                'Canadian Eskimo Dog',
                'Cane Corso',
                'Cao da Serra de Aires',
                'Caravan Hound',
                'Cardigan Welsh Corgi',
                'Carolina Dog',
                'Carpathian Sheepdog',
                'Catahoula Bulldog',
                'Catahoula Leopard Dog',
                'Catalan Sheepdog',
                'Caucasian Ovtcharka',
                'Cavalier King Charles Spaniel',
                'Central Asian Ovtcharka',
                'Cesky Fousek',
                'Cesky Terrier',
                'Chart Polski',
                'Chesapeake Bay Retriever',
                'Chihuahua',
                'Chinese Crested',
                'Chinook',
                'Chippiparai',
                'Chizer',
                'Chorkie',
                'Chow Chow',
                "Cirneco dell'Etna",
                'Clumber Spaniel',
                'Cockalier',
                'Cockapoo',
                'Collie',
                'Coton De Tulear',
                'Cotonese',
                'Croatian Sheepdog',
                'Curly-Coated Retriever',
                'Czechoslovakian Wolfdog',
                'Dachshund',
                'Dalmatian',
                'Dandie Dinmont Terrier',
                'Danish-Swedish Farmdog',
                'Deutsche Bracke',
                'Dingo',
                'Doberman Pinscher',
                'Dogo Argentino',
                'Dogue de Bordeaux',
                'Dorgi',
                'Dorkie',
                'Double Doodle',
                'Dretse Patrijshond',
                'Drever',
                'Dunker',
                'Dutch Shepherd Dog',
                'Dutch Smoushond',
                'East Siberian Laika',
                'East-European Shepherd',
                'English Cocker Spaniel',
                'English Foxhound',
                'English Setter',
                'English Shepherd',
                'English Springer Spaniel',
                'English Toy Spaniel',
                'Entlebucher Mountain Dog',
                'Eurasier',
                'Field Spaniel',
                'Fila Brasileiro',
                'Finnish Hound',
                'Finnish Lapphund',
                'Finnish Spitz',
                'Flat-Coated Retriver',
                'Francais Blanc et Noir',
                'French Bulldog',
                'French Spaniel',
                'German Longhaired Pointer',
                'German Pincher',
                'German Shepherd',
                'German Shorthaired Pointer',
                'German Wirehaired Pointer',
                'Giant Schnauzer',
                'Glen of Imaan Terrier',
                'Golden Retriever',
                'Goldendoodle',
                'Gordon Setter',
                'Grand Basset Griffon Vendeen',
                'Grand Bleu de Gascogne',
                'Great Dane',
                'Great Pyrenees',
                'Greater Swiss Mountain Dog',
                'Greenland Dog',
                'Greyhound',
                'Griffon bleu de Gascogne',
                'Hamilton Hound',
                'Harrier',
                'Havanese',
                'Hokkaido Dog',
                'Hovawart',
                'Ibizan Hound',
                'Icelandic Sheepdog',
                'Irish Red and White Setter',
                'Irish Setter',
                'Irish Terrier',
                'Irish Water Spaniel',
                'Irish Wolfhound',
                'Italian Greyhound',
                'Jack Russell Terrier',
                'Jagdterrier',
                'Jamthund',
                'Japanese Chin',
                'Japanese Spitz',
                'Japanese Terrier',
                'Kangal Dog',
                'Karelian Bear Dog',
                'Karst Shepherd',
                'Keeshond',
                'Kerry Blue Terrier',
                'King Shepherd',
                'Kishu Ken',
                'Komondor',
                'Kooikerhondje',
                'Koolie',
                'Korean Jindo',
                'Kromfohrlander',
                'Kuvasz',
                'Kyi-Leo',
                'Labrador Retriever',
                'Lagotto Romagnolo',
                'Lakeland Terrier',
                'Lancashire Heeler',
                'Landseer',
                'Lapponian Herder',
                'Large Munsterlander',
                'Leonberger',
                'Lhasa Apso',
                'Lowchen',
                'Lucas Terrier',
                'Lurcher',
                'Majestic Tree Hound',
                'Mal-Shi',
                'Maltese',
                'Manchester Terrier',
                'Maremma Sheepdog',
                'Mastiff',
                'McNab',
                'Miniature American Shepherd',
                'Miniature Bull Terrier',
                'Miniature Bulldog',
                'Miniature Pinscher',
                'Miniature Poodle',
                'Miniature Schnauzer',
                'Miniature Shar Pei',
                'Moscow Watchdog',
                'Mountain Cur',
                'Mountain Feist',
                'Mudi',
                'Neapolitan Mastiff',
                'New Guinea Singing Dog',
                'Newfoundland',
                'Norfolk Terrier',
                'Norrbottenspets',
                'Northern Inuit Dog',
                'Norwegian Buhund',
                'Norwegian Elkhound',
                'Norwegian Lundehund',
                'Norwich Terrier',
                'Nova Scotia Duck Tooling Retriever',
                'Old English Sheepdog',
                'Olde English Bulldogge',
                'Otterhound',
                'Pakistani Mastiff',
                'Papillon',
                'Parson Russell Terrier',
                'Patterdale Terrier',
                'Pekingese',
                'Pembroke Welsh Corgi',
                'Perro de Presa Canario',
                'Perro de Presa Mallorquin',
                'Peruvian Inca Orchid',
                'Petit Basset Griffon Vendeen',
                'Pharaoh Hound',
                'Picardy Spaniel',
                'Plott Hound',
                'Plummer Terrier',
                'Pointer',
                'Polish Hunting Dog',
                'Polish Lowland Sheepdog',
                'Polish Tatra Sheepdog',
                'Pomeranian',
                'Pont-Audemer Spaniel',
                'Poodle',
                'Portuguese Podengo Pequeno',
                'Portuguese Pointer',
                'Portuguese Water Dog',
                'Prazsky Krysarik',
                'Pudelpointer',
                'Pug',
                'Puggle',
                'Puli',
                'Pumi',
                'Pyrenean Mastiff',
                'Pyrenean Shepherd',
                'Rafeiro do Alentejo',
                'Rajapalayam dog',
                'Rat Terrier',
                'Redbone Coonhound',
                'Rhodesian Ridgeback',
                'Romanian Mioritic Shepherd Dog',
                'Rottweiler',
                'Russian Spaniel',
                'Russian Toy',
                'Russian Tsvetnaya Bolonka',
                'Saarloos wolfdog',
                'Saluki',
                'Samoyed',
                'Sapsali',
                'Sarplaninac',
                'Schapendoes',
                'Schipperke',
                'Scottish Deerhound',
                'Scottish Terrier',
                'Sealyham Terrier',
                'Seppala Siberian Sleddog',
                'Serbian Hound',
                'Shar-Pei',
                'Shetland Sheepdog',
                'Shiba Inu',
                'Shichon',
                'Shih Tzu',
                'Shikoku dog',
                'Shiloh Shepherd dog',
                'Siberian Husky',
                'Silken Windhound',
                'Silky Terrier',
                'Skye Terrier',
                'Sloughi',
                'Slovensky Cuvac',
                'Smaland Hound',
                'Small Munsterlander',
                'Smooth Fox Terrier',
                'Soft Coated Wheaten Terrier',
                'South Russian Ovcharka',
                'Spanish Greyhound',
                'Spanish Mastiff',
                'Spanish Water Dog',
                'Spinone Italiano',
                'St. Bernard',
                'Stabyhoun',
                'Staffordshire Bull Terrier',
                'Standard Schnauzer',
                'Sussex Spaniel',
                'Swedish Lapphund',
                'Swedish Vallhund',
                'Taco Terrier',
                'Tamaskan Dog',
                'Texas Heeler',
                'Thai Bangkaew Dog',
                'Thai Ridgeback',
                'Tibetan Mastiff',
                'Tibetan Spaniel',
                'Tibetan Terrier',
                'Tornjak',
                'Tosa Ken',
                'Toy Fox Terrier',
                'Toy Poodle',
                'Transylvanian Hound',
                'Treeing Walker Coonhound',
                'Vizsla',
                'Volpino Italiano',
                'Weimaraner',
                'Welsh Springer Spaniel',
                'Welsh Terrier',
                'West Highland White Terrier',
                'West Siberian Laika',
                'Wetterhoun',
                'Whippet',
                'Wire Fox Terrier',
                'Wirehaired Pointing Griffon',
                'Wirehaired Vizsla',
                'Xoloitzcuintli',
                'Yorkshire Terrier',
            ]);
        }

        if ($cat) {
            $this->seedBreedList($cat->id, [
                'Other',
                'American Shorthair',
                'Abyssinian',
                'American Curl',
                'American Bobtail',
                'American Wirehair',
                'Aegean',
                'Australian Mist',
                'American Polydactyl',
                'Arabian Mau',
                'Asian cat',
                'Asian Semi-longhair',
                'British Shorthair',
                'Bengal',
                'Burmese',
                'Birman',
                'Chantilly-Tiffany',
                'Balinese',
                'Bombay',
                'Burmilla',
                'Bambino',
                'Brazilian Shorthair',
                'British Longhair',
                'Cornish Rex',
                'Colorpoint Shorthair',
                'Chartreux',
                'California Spangled',
                'Cymric',
                'Chausie',
                'Cheetoh',
                'Cyprus',
                'Devon Rex',
                'Donskoy',
                'Dwelf',
                'Exotic Shorthair',
                'Egyptian Mau',
                'European Burmese',
                'Elf cat',
                'Havana Brown',
                'Himalayan',
                'Japanese Bobtail',
                'Javanese',
                'Khao Manee',
                'Korat',
                'Lykoi',
                'LaPerm',
                'Maine Coon',
                'Manx',
                'Munchkin',
                'Minskin',
                'Norwegian Forest Cat',
                'Nebelung',
                'Napoleon cat',
                'Oriental',
                'Ocicat',
                'Persian',
                'Pixie-bob',
                'Peterbald',
                'Ragamuffin',
                'Rogdoll',
                'Puspin',
                'Somali',
                'Savannah',
                'Serengeti cat',
                'Siamese',
                'Scottish Fold',
                'Sokoke',
                'Siberian',
                'Russian Blue',
                'Singapura',
                'Snowshoe',
                'Selkirk Rex',
                'Tiffanie',
                'Toyger',
                'Turkish Angora',
                'Tonskinese',
                'Tabby',
                'Turkish Van',
                'Ukrainian Levkoy',
                'Sphynx',
                'Chinchilla',
                'Oriental Long Hair',
                'Ragdoll',
                'Thai cat',
                'York Chocolate',
            ]);
        }
    }
}
